### ISSUE TITLE
Put archv2.tar.xz in another mirror

### ISSUE THREAD

**Issue by helloitu** [whitehax0r/ArchLinux-PS4v2#2]
Hi, can you please store this file [archv2.tar.xz](https://mega.nz/file/vn5glJbB#ZWSZA7scPuyx1UkOiM_UW7NoUxxMc_L3pJGiUWKbmRI) in another website? bc of mega limitations...

**Comment by zqpvr** [comment]
what do you mean

**Comment by whitehax0r** [comment]
what limitation, just wait for the next day and you will be able to download the file or use a VPN.
